"""
Google News catalogues: the topics, languages and countries the API accepts.

Static data only. Moved verbatim out of app.api.google_news.google_news_api,
which still re-exports every name here.
"""

AVAILABLE_TOPICS = [
    "WORLD",
    "NATION",
    "BUSINESS",
    "TECHNOLOGY",
    "ENTERTAINMENT",
    "SPORTS",
    "SCIENCE",
    "HEALTH",
    "POLITICS",
    "CELEBRITIES",
    "TV",
    "MUSIC",
    "MOVIES",
    "THEATER",
    "SOCCER",
    "CYCLING",
    "MOTOR SPORTS",
    "TENNIS",
    "COMBAT SPORTS",
    "BASKETBALL",
    "BASEBALL",
    "FOOTBALL",
    "SPORTS BETTING",
    "WATER SPORTS",
    "HOCKEY",
    "GOLF",
    "CRICKET",
    "RUGBY",
    "ECONOMY",
    "PERSONAL FINANCE",
    "FINANCE",
    "DIGITAL CURRENCIES",
    "MOBILE",
    "ENERGY",
    "GAMING",
    "INTERNET SECURITY",
    "GADGETS",
    "VIRTUAL REALITY",
    "ROBOTICS",
    "NUTRITION",
    "PUBLIC HEALTH",
    "MENTAL HEALTH",
    "MEDICINE",
    "SPACE",
    "WILDLIFE",
    "ENVIRONMENT",
    "NEUROSCIENCE",
    "PHYSICS",
    "GEOLOGY",
    "PALEONTOLOGY",
    "SOCIAL SCIENCES",
    "EDUCATION",
    "JOBS",
    "ONLINE EDUCATION",
    "HIGHER EDUCATION",
    "VEHICLES",
    "ARTS-DESIGN",
    "BEAUTY",
    "FOOD",
    "TRAVEL",
    "SHOPPING",
    "HOME",
    "OUTDOORS",
    "FASHION",
]

AVAILABLE_LANGUAGES = {
    "english": "en",
    "indonesian": "id",
    "czech": "cs",
    "german": "de",
    "spanish": "es-419",
    "french": "fr",
    "italian": "it",
    "latvian": "lv",
    "lithuanian": "lt",
    "hungarian": "hu",
    "dutch": "nl",
    "norwegian": "no",
    "polish": "pl",
    "portuguese brasil": "pt-419",
    "portuguese portugal": "pt-150",
    "romanian": "ro",
    "slovak": "sk",
    "slovenian": "sl",
    "swedish": "sv",
    "vietnamese": "vi",
    "turkish": "tr",
    "greek": "el",
    "bulgarian": "bg",
    "russian": "ru",
    "serbian": "sr",
    "ukrainian": "uk",
    "hebrew": "he",
    "arabic": "ar",
    "marathi": "mr",
    "hindi": "hi",
    "bengali": "bn",
    "tamil": "ta",
    "telugu": "te",
    "malyalam": "ml",
    "thai": "th",
    "chinese simplified": "zh-Hans",
    "chinese traditional": "zh-Hant",
    "japanese": "ja",
    "korean": "ko",
}

AVAILABLE_COUNTRIES = {
    "Australia": "AU",
    "Botswana": "BW",
    "Canada": "CA",
    "Ethiopia": "ET",
    "Ghana": "GH",
    "India": "IN",
    "Indonesia": "ID",
    "Ireland": "IE",
    "Israel": "IL",
    "Kenya": "KE",
    "Latvia": "LV",
    "Malaysia": "MY",
    "Namibia": "NA",
    "New Zealand": "NZ",
    "Nigeria": "NG",
    "Pakistan": "PK",
    "Philippines": "PH",
    "Singapore": "SG",
    "South Africa": "ZA",
    "Tanzania": "TZ",
    "Uganda": "UG",
    "United Kingdom": "GB",
    "United States": "US",
    "Zimbabwe": "ZW",
    "Czech Republic": "CZ",
    "Germany": "DE",
    "Austria": "AT",
    "Switzerland": "CH",
    "Argentina": "AR",
    "Chile": "CL",
    "Colombia": "CO",
    "Cuba": "CU",
    "Mexico": "MX",
    "Peru": "PE",
    "Venezuela": "VE",
    "Belgium": "BE",
    "France": "FR",
    "Morocco": "MA",
    "Senegal": "SN",
    "Italy": "IT",
    "Lithuania": "LT",
    "Hungary": "HU",
    "Netherlands": "NL",
    "Norway": "NO",
    "Poland": "PL",
    "Brazil": "BR",
    "Portugal": "PT",
    "Romania": "RO",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Sweden": "SE",
    "Vietnam": "VN",
    "Turkey": "TR",
    "Greece": "GR",
    "Bulgaria": "BG",
    "Russia": "RU",
    "Ukraine": "UA",
    "Serbia": "RS",
    "United Arab Emirates": "AE",
    "Saudi Arabia": "SA",
    "Lebanon": "LB",
    "Egypt": "EG",
    "Bangladesh": "BD",
    "Thailand": "TH",
    "China": "CN",
    "Taiwan": "TW",
    "Hong Kong": "HK",
    "Japan": "JP",
    "Republic of Korea": "KR",
}
