#!/usr/bin/env python3
"""
Generate docs/API_REFERENCE.md from the application's OpenAPI schema.

The hand-written reference drifted from the real API (it covered 26 of the 54
/api/v1 paths), so the reference is now rendered straight from
``main.app.openapi()``. tests/test_api_reference.py fails when the committed
file differs from what this script would produce.

Usage:
    python scripts/generate_api_reference.py           # rewrite the file
    python scripts/generate_api_reference.py --check   # exit 1 if it is stale

Only route-derived parts of the schema are rendered. ``info`` (title, version,
description) and anything else that comes from settings is deliberately left
out so the output is identical in every environment.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "API_REFERENCE.md"
REGENERATE_COMMAND = "python scripts/generate_api_reference.py"

HEADER_COMMENT = "<!-- Generated by scripts/generate_api_reference.py from the OpenAPI schema. Do not edit by hand. -->"

# Sections appear in this order; any tag not listed follows, alphabetically.
TAG_ORDER = [
    "Google Autocomplete API",
    "Google News API",
    "Google Trends API",
    "YouTube Transcripts API",
    "Google Maps API",
    "Health",
    "Configuration",
]
UNTAGGED = "Other"

HTTP_METHODS = ["get", "post", "put", "patch", "delete", "head", "options", "trace"]

SCHEMA_REF_PREFIX = "#/components/schemas/"


def load_openapi() -> dict[str, Any]:
    """Import the application and return its OpenAPI schema."""
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    import main

    return main.app.openapi()


def _cell(text: Any) -> str:
    """Make a value safe for a single Markdown table cell."""
    text = re.sub(r"\s+", " ", str(text)).strip()
    return text.replace("|", "\\|")


def _ref_name(ref: str) -> str:
    return ref[len(SCHEMA_REF_PREFIX) :] if ref.startswith(SCHEMA_REF_PREFIX) else ref


def _type_name(schema: dict[str, Any] | None) -> str:
    """Render a JSON schema as a compact type expression."""
    if not schema:
        return "any"
    if "$ref" in schema:
        return _ref_name(schema["$ref"])
    for key in ("anyOf", "oneOf"):
        if key in schema:
            parts: list[str] = []
            for option in schema[key]:
                name = _type_name(option)
                if name not in parts:
                    parts.append(name)
            return " | ".join(parts)
    if "allOf" in schema and len(schema["allOf"]) == 1:
        return _type_name(schema["allOf"][0])
    if "enum" in schema:
        return "enum(" + ", ".join(json.dumps(v) for v in schema["enum"]) + ")"
    schema_type = schema.get("type")
    if schema_type == "array":
        return f"array[{_type_name(schema.get('items'))}]"
    if isinstance(schema_type, list):
        return " | ".join(schema_type)
    if schema_type:
        return f"{schema_type} ({schema['format']})" if "format" in schema else schema_type
    return "any"


def _default(schema: dict[str, Any]) -> str:
    if "default" not in schema:
        return ""
    return "`" + json.dumps(schema["default"], sort_keys=True) + "`"


def _body_schema(content: dict[str, Any]) -> str:
    """Describe a request/response ``content`` map as ``type`` or ``media: type``."""
    rendered = []
    for media_type in sorted(content):
        schema = content[media_type].get("schema")
        name = _type_name(schema) if schema else "any"
        rendered.append(f"`{name}`" if media_type == "application/json" else f"`{media_type}`: `{name}`")
    return ", ".join(rendered)


def _render_operation(method: str, path: str, op: dict[str, Any]) -> list[str]:
    lines = [f"### {method.upper()} {path}", ""]
    summary = op.get("summary") or op.get("operationId", "")
    if summary:
        lines += [_cell(summary), ""]

    auth = "`X-API-Key` header" if op.get("security") else "none"
    lines.append(f"- **Auth:** {auth}")

    body = op.get("requestBody")
    if body:
        required = "required" if body.get("required") else "optional"
        lines.append(f"- **Request body** ({required}): {_body_schema(body.get('content', {}))}")

    responses = op.get("responses", {})
    success = sorted(code for code in responses if code.startswith("2"))
    if success:
        code = success[0]
        content = responses[code].get("content")
        described = _body_schema(content) if content else "no body"
        if described == "`any`":
            described = "JSON (no response model declared)"
        lines.append(f"- **Response {code}:** {described}")
    lines.append("")

    params = op.get("parameters", [])
    if params:
        lines += [
            "| Name | In | Type | Required | Default | Description |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        in_order = {"path": 0, "query": 1, "header": 2, "cookie": 3}
        for param in sorted(params, key=lambda p: (in_order.get(p["in"], 9), p["name"])):
            schema = param.get("schema", {})
            description = param.get("description") or schema.get("description") or ""
            row = [
                f"`{param['name']}`",
                param["in"],
                f"`{_cell(_type_name(schema))}`",
                "yes" if param.get("required") else "no",
                _cell(_default(schema)),
                _cell(description),
            ]
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")
    return lines


def _anchor(heading: str) -> str:
    """GitHub-style anchor for a heading."""
    slug = re.sub(r"[^\w\- ]", "", heading.lower())
    return slug.replace(" ", "-")


def render(schema: dict[str, Any]) -> str:
    """Render the Markdown reference for an OpenAPI schema."""
    sections: dict[str, list[tuple[str, str, dict[str, Any]]]] = {}
    for path in sorted(schema.get("paths", {})):
        item = schema["paths"][path]
        for method in HTTP_METHODS:
            if method not in item:
                continue
            op = item[method]
            tags = op.get("tags") or [UNTAGGED]
            sections.setdefault(tags[0], []).append((method, path, op))

    ordered_tags = [t for t in TAG_ORDER if t in sections]
    ordered_tags += sorted(t for t in sections if t not in TAG_ORDER)

    operation_count = sum(len(ops) for ops in sections.values())
    v1_paths = sum(1 for p in schema.get("paths", {}) if p.startswith("/api/v1/"))

    lines = [
        HEADER_COMMENT,
        "",
        "# API Reference",
        "",
        f"Every HTTP operation Headwater exposes: {operation_count} operations on {len(schema.get('paths', {}))} "
        f"paths, {v1_paths} of them under `/api/v1`. This file is generated from the application's OpenAPI schema, so it lists what the "
        f"code actually serves. To refresh it after changing an endpoint, run `{REGENERATE_COMMAND}`.",
        "",
        "## Basics",
        "",
        "- **Base path:** the data APIs live under `/api/v1` (for example `/api/v1/google-news/search/`). "
        "The health and configuration endpoints sit at the root.",
        "- **Authentication:** send your key in the `X-API-Key` request header. Operations marked "
        "**Auth: none** below accept requests without it.",
        "- **Interactive docs:** outside production the service serves Swagger UI at `/api/docs`, ReDoc at "
        "`/api/redoc` and the raw OpenAPI schema at `/openapi.json`. In production none of these are "
        "registered, so fetch the schema from a non-production instance or run this script.",
        "- **Schemas:** request and response types named below are the component schemas in the OpenAPI "
        "document (`components.schemas`), where their fields are listed in full.",
        "",
        "## Contents",
        "",
    ]
    for tag in ordered_tags:
        lines.append(f"- [{tag}](#{_anchor(tag)}) ({len(sections[tag])})")
    lines.append("")

    for tag in ordered_tags:
        lines += [f"## {tag}", ""]
        for method, path, op in sections[tag]:
            lines += _render_operation(method, path, op)

    return "\n".join(lines).rstrip("\n") + "\n"


def main_cli(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0].strip())
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if docs/API_REFERENCE.md differs from the generated output instead of writing it",
    )
    args = parser.parse_args(argv)

    expected = render(load_openapi())
    relative = OUTPUT_PATH.relative_to(REPO_ROOT)

    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else None
        if current != expected:
            print(f"{relative} is out of date with the OpenAPI schema. Run: {REGENERATE_COMMAND}", file=sys.stderr)
            return 1
        print(f"{relative} is up to date.")
        return 0

    OUTPUT_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Wrote {relative}")
    return 0


if __name__ == "__main__":
    sys.exit(main_cli())
